### ISSUE TITLE
Android correction

### ISSUE THREAD

**Issue by papattes** [ogoguel/cordova-plugin-native-logs#1]
Hello ! 

In NativeLogs::getLogsFromLogCat :
Add "nb++" to exit the while when you have reached the desired number of lines

**Comment by papattes** [comment]
Oops, sorry ...
Hello ! : D

**Comment by ogoguel** [comment]
Thanks fio having spotted that : definitely a mistake. #notproud

Can you submit a PR? 
Cheers

**Comment by ogoguel** [comment]
Fixed!
