### ISSUE TITLE
ENOENT error during plugin installation

### ISSUE THREAD

**Issue by neuralpha** [ogoguel/cordova-plugin-native-logs#2]
I got the following error with a failed installation -
`ENOENT: no such file or directory, open <mypath>/plugins/cordova-plugin-native-logs/www/nativeLogs.js`

It was fixed by copying `www/nativeLogs.js` from repo.
Perhaps the npm repo has not been updated ?

**Comment by ogoguel** [comment]
Due to invalid .npmignore definition
Fixed in 1.0.5 
Tx!
