### ISSUE TITLE
Android works / iOS not

### ISSUE THREAD

**Issue by nowrap** [ogoguel/cordova-plugin-native-logs#3]
Hello,
today i integrated your plugin in my ionic 3 app.

Under android i get results from the NativeLogs.getLog  callback.
Under iOS the callback isn't triggered.

XCode says:
`2019-02-26 16:37:15.542520+0100 S12[505:65624] CDVPlugin class
CDVNativeLogs (pluginName: NativeLogs) does not exist.
2019-02-26 16:37:15.542564+0100 S12[505:65624] ERROR: Plugin
'NativeLogs' not found, or is not a CDVPlugin. Check your plugin mapping
in config.xml.
2019-02-26 16:37:15.542613+0100 S12[505:65624] FAILED pluginJSON =
["NativeLogs809611558","NativeLogs","getLog",[1000,false]]`

Any advices?

Regards
.nowrap

**Comment by ogoguel** [comment]
Sounds like the plugin has not been loaded : can you check that you have the following line in your plugin.xml file (you need to use --save when using the plugin add command) 
`<plugin name="cordova-plugin-native-logs" spec="1.0.5" />`

If it does not work, paste the output of the ionic info

**Comment by nowrap** [comment]
Hello,
thanks for your help.

config.xml includes your mentioned line:
`<plugin name="cordova-plugin-native-logs" spec="1.0.5" />`

My ionic info on windows is:

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.10.3 (C:\Users\nowrap\AppData\Roaming\npm\node_modules\ionic)
>    Ionic Framework    : ionic-angular 3.9.4
>    @ionic/app-scripts : 3.2.2
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.4, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 19 other plugins)
> 
> System:
> 
>    NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
>    npm    : 6.8.0
>    OS     : Windows 10

And on the mac:

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.10.3 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.4
>    @ionic/app-scripts : 3.2.2
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3,(and 21 other plugins)
> 
> System:
> 
>    ios-deploy : 1.9.4
>    NodeJS     : v10.15.1 (/usr/local/bin/node)
>    npm        : 6.8.0
>    OS         : macOS Mojave
>    Xcode      : Xcode 10.1 Build version 10B61

The mac/ios version has 3 more plugins:
acidhax.cordova.chromecast 0.0.1-alpha "Cordova ChromeCast"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-zeroconf 1.3.3 "ZeroConf"

And the cordova-plugin-ionic version differs.

**Comment by ogoguel** [comment]
I've tested the sample application (https://github.com/ogoguel/cordova-plugin-native-logs/tree/master/sample) with the same configuration without any issue.

Can you test it on your mac machine, and if it works, try adding your additional plugins to see if there could be some compatibility issue?

Also, check your XCodeProject to see if the the plugin source code (CDVNativeLogs.m) is actually added to the project ? (in the plugins/ folder)
Let me know

```

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : not installed
   @angular-devkit/schematics    : not installed
   @angular/cli                  : not installed
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   NodeJS : v8.11.2 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```
