### ISSUE TITLE
iOS logs only show events since the last App launch

### ISSUE THREAD

**Issue by simonwatt** [ogoguel/cordova-plugin-native-logs#4]
I haven't tried in Android, but when I use this plugin on iOS as per the documentation:
```
NativeLogs.getLog(1000,false, function(_logs) {
// do something w/ the logs
}
```
The exported log only shows the log since the app was last opened, even if it is much less than 1000 lines. Is there a way to get prior logs too?

**Comment by ogoguel** [comment]
No, it is not possible.  You can only retrieve the logs from the current session (ie: live logs).
